# # SQLite version 3.x
# #   gem install sqlite3
# #
# #   Ensure the SQLite 3 gem is defined in your Gemfile
# #   gem 'sqlite3'
# #
# default: &default
#   adapter: mysql2
#   encoding: utf8
#   pool: 5
#   username: root
#   host: 127.0.0.1
#   variables:
#     sql_mode: TRADITIONAL # https://github.com/rails/rails/issues/25924

# development: &development
#   <<: *default
#   database: aws_elastic_search


# development_standby:
#   <<: *development

# test:
#   <<: *default
#   database: aws_elastic_search_test



default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>
  port: <%= ENV['MYSQL_PORT'] %>

development:
  <<: *default
  database: the-greatest-rails-app-ever_development

staging:
  <<: *default
  database: the-greatest-rails-app-ever_staging

test:
  <<: *default
  database: the-greatest-rails-app-ever_test

production:
  <<: *default
  database: the-greatest-rails-app-ever_production